name: Tests
on: [push]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build
      run: yarn
  
    - name: Unit Tests
      run: yarn test:unit

    - name: Integration Tests
      run: yarn test:integration
